name: Angular-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1
    - name: npm install
      working-directory: app/whiteboard
      run: npm install
    - name: ng build
      working-directory: app/whiteboard
      run: ./node_modules/.bin/ng build --prod